### ISSUE TITLE
Where to post examples, etc?

### ISSUE THREAD

**Issue by RdR1024** [friguzzi/cplint#4]
Hi Fabrizio,

Thanks for making cplint available for SWIPL.  I was previously using ProbLog, but I really like having a similar library available for swipl.   I was playing around with cplint, and did a little example which possibly others might like.  But I wasn't sure where best to post it (the review of cplint on SWI had problems).

Anyway, here's my little example: Monte Hall in basically 4 lines of probability logic:

```
% Monte Hall for swi-prolog + cplint

:- use_module(library(pita)).
:- pita.
:- begin_lpad.

picked(car):1/3.
picked(goat):- \+ picked(car).

revealed(goat):- picked(_).

switch_gets(car):- picked(goat), revealed(goat).

:- end_lpad.

main:-
    prob(switch_gets(car),P),
    format('Probability that switching gets the car is ~2f',[P]).
```

**Comment by RdR1024** [comment]
Oops, Git isn't nice to my prolog code, because \\+ is changed to +

**Comment by friguzzi** [comment]
Hi,
what you can do is to save your file using a meaningful name with the File->Save swish menu option. Then the file is assigned a url that you can post. I created an example at
http://cplint.lamping.unife.it/p/monty_simple.pl
If you like this example, I can add it to the list of examples, so that later it can be accessed at
http://cplint.lamping.unife.it/example/inference/monty_simple.pl
If you have modifications, you can do them at that url and then choose File-> Save
There is also a google group you can use for posting
https://groups.google.com/forum/#!forum/cplint
If you want other examples to be added to cplint on swish, please let us know, we will be happy to add them.

Best
Fabrzio

**Comment by RdR1024** [comment]
Thanks, Fabrizio -- I've made minor edits.  One thing that regularly
catches me is that some (web based) text editors change the Prolog + to +.

Looks fine now.

Thanks for pointing out the SWISH method for creating examples.

cheers,

RdR

**Comment by friguzzi** [comment]
Hi,
it is online at
http://cplint.lamping.unife.it/example/inference/monty_simple.pl

Thanks
Fabrizio

2016-09-14 22:28 GMT+02:00 RdR notifications@github.com:
